### ISSUE TITLE
Does not work for redmine Redmine 3.4.5.stable

### ISSUE THREAD

**Issue by gorhas** [speedy32129/projects_show#5]
Don't seems to work at all for current redmine...

**Comment by dskibarko** [comment]
I am confirm this issue for Redmine 3.4.5

**Comment by mauriziotallarico** [comment]
I also confirm: 404 error on 3.4.5
Thanks and appreciate quick response:)

**Comment by dskibarko** [comment]
Log for investigation

Started GET "/redmine/projects/vesta_additional_function_bcu_version_1" for 127.0.0.1 at 2018-07-23 14:21:37 +0300
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"vesta_additional_function_bcu_version_1"}
  Current user: skibarko (id=1)
  Rendered projects/_members_box.html.erb (15.6ms)
  Rendered plugins/plus_gantt/app/views/plusgantt/_project_show_right.html.erb (0.0ms)
  Rendered plugins/projects_show/app/views/projects/_show_3.x.html.erb (1747.2ms)
  Rendered plugins/projects_show/app/views/projects/show.html.erb within layouts/base (1981.2ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered plugins/bestest_timer/app/views/bestest_timer/_bestest_timer_partial.html.erb (0.0ms)
  Rendered plugins/deployer/app/views/hooks/_select2.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (15.6ms)
Completed 404 Not Found in 3073ms (Views: 576.0ms | ActiveRecord: 78.0ms)
Started GET "/redmine/javascripts/redmine_extensions/dynamic_loading.js" for 127.0.0.1 at 2018-07-23 14:21:41 +0300

ActionController::RoutingError (No route matches [GET] "/javascripts/redmine_extensions/dynamic_loading.js"):
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.9) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.9) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.9) lib/rack/content_length.rb:15:in `call'
  rack (1.6.9) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  railties (4.2.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.8) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.9) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.9) lib/rack/urlmap.rb:50:in `each'
  rack (1.6.9) lib/rack/urlmap.rb:50:in `call'
  thin-1.6.2-x86 (mingw32) lib/thin/connection.rb:86:in `block in pre_process'
  thin-1.6.2-x86 (mingw32) lib/thin/connection.rb:84:in `catch'
  thin-1.6.2-x86 (mingw32) lib/thin/connection.rb:84:in `pre_process'
  thin-1.6.2-x86 (mingw32) lib/thin/connection.rb:53:in `process'
  thin-1.6.2-x86 (mingw32) lib/thin/connection.rb:39:in `receive_data'
  eventmachine-1.2.5-x86 (mingw32) lib/eventmachine.rb:194:in `run_machine'
  eventmachine-1.2.5-x86 (mingw32) lib/eventmachine.rb:194:in `run'
  thin-1.6.2-x86 (mingw32) lib/thin/backends/base.rb:73:in `start'
  thin-1.6.2-x86 (mingw32) lib/thin/server.rb:162:in `start'
  thin-1.6.2-x86 (mingw32) lib/thin/controllers/controller.rb:87:in `start'
  thin-1.6.2-x86 (mingw32) lib/thin/runner.rb:199:in `run_command'
  thin-1.6.2-x86 (mingw32) lib/thin/runner.rb:155:in `run!'
  thin-1.6.2-x86 (mingw32) bin/thin:6:in `<top (required)>'
  bin/thin:29:in `load'
  bin/thin:29:in `<main>'
